name: Bundle Modxo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:
  
jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib

      - name: Get Pico SDK
        run: git clone --branch 2.0.0 --recurse-submodules https://github.com/raspberrypi/pico-sdk.git

      - name: Create Build Folder
        run: |
          mkdir build
          mkdir output

      - name: Build Modxo Official Pico2
        run: |
          cd ${{ github.workspace }}/build
          cmake -DPICO_SDK_PATH=${{ github.workspace }}/pico-sdk -DMODXO_PINOUT=official_pico2 .. 
          cmake --build .
          cp ${{ github.workspace }}/build/modxo_official_pico2.bin ${{ github.workspace }}/output/modxo_official_pico2.bin
          cp ${{ github.workspace }}/build/modxo_official_pico2.uf2 ${{ github.workspace }}/output/modxo_official_pico2.uf2

      - name: Build Modxo Official Pico
        run: |
          cd ${{ github.workspace }}/build
          rm -fr ./*
          cmake -DPICO_SDK_PATH=${{ github.workspace }}/pico-sdk -DMODXO_PINOUT=official_pico .. 
          cmake --build .
          cp ${{ github.workspace }}/build/modxo_official_pico.bin ${{ github.workspace }}/output/modxo_official_pico.bin
          cp ${{ github.workspace }}/build/modxo_official_pico.uf2 ${{ github.workspace }}/output/modxo_official_pico.uf2

      - name: Build Modxo YD-RP2040
        run: |
          cd ${{ github.workspace }}/build
          cmake -DPICO_SDK_PATH=${{ github.workspace }}/pico-sdk -DMODXO_PINOUT=yd_rp2040 .. 
          cmake --build .
          cp ${{ github.workspace }}/build/modxo_yd_rp2040.bin ${{ github.workspace }}/output/modxo_yd_rp2040.bin
          cp ${{ github.workspace }}/build/modxo_yd_rp2040.uf2 ${{ github.workspace }}/output/modxo_yd_rp2040.uf2

      - name: Build Modxo RP2040-Zero-Tiny
        run: |
          cd ${{ github.workspace }}/build
          cmake -DPICO_SDK_PATH=${{ github.workspace }}/pico-sdk -DMODXO_PINOUT=rp2040_zero_tiny .. 
          cmake --build .
          cp ${{ github.workspace }}/build/modxo_rp2040_zero_tiny.bin ${{ github.workspace }}/output/modxo_rp2040_zero_tiny.bin
          cp ${{ github.workspace }}/build/modxo_rp2040_zero_tiny.uf2 ${{ github.workspace }}/output/modxo_rp2040_zero_tiny.uf2

      - name: Build Modxo XIAO-RP2040
        run: |
          cd ${{ github.workspace }}/build
          cmake -DPICO_SDK_PATH=${{ github.workspace }}/pico-sdk -DMODXO_PINOUT=xiao_rp2040 .. 
          cmake --build .
          cp ${{ github.workspace }}/build/modxo_xiao_rp2040.bin ${{ github.workspace }}/output/modxo_xiao_rp2040.bin
          cp ${{ github.workspace }}/build/modxo_xiao_rp2040.uf2 ${{ github.workspace }}/output/modxo_xiao_rp2040.uf2

      - name: Build Modxo Ultra
        run: |
          cd ${{ github.workspace }}/build
          cmake -DPICO_SDK_PATH=${{ github.workspace }}/pico-sdk -DMODXO_PINOUT=ultra .. 
          cmake --build .
          cp ${{ github.workspace }}/build/modxo_ultra.bin ${{ github.workspace }}/output/modxo_ultra.bin
          cp ${{ github.workspace }}/build/modxo_ultra.uf2 ${{ github.workspace }}/output/modxo_ultra.uf2

      - name: List Files
        run: ls ${{ github.workspace }}/build

      - name: Create Draft Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          draft: true
          files: |
            ${{ github.workspace }}/output/*.bin
            ${{ github.workspace }}/output/*.uf2

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ github.workspace }}/output/*.bin
            ${{ github.workspace }}/output/*.uf2

